SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

DROP TABLE IF EXISTS `mydb`.`NIVELES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NIVELES` (
  `ID_NIVEL` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_NIVEL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_NIVEL`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`ASUNTO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ASUNTO` (
  `ID_ASUNTO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_ASUNTO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ASUNTO`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`MUNICIPIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MUNICIPIO` (
  `ID_MUNICIPIO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_MUNICIPIO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_MUNICIPIO`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`ALUMNO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ALUMNO` (
  `CURP` VARCHAR(45) NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `APELLIDO_PAT` VARCHAR(45) NULL,
  `APELLIDO_MAT` VARCHAR(45) NULL,
  `TELEFONO` VARCHAR(10) NULL,
  `CELULAR` VARCHAR(10) NULL,
  `EMAIL` VARCHAR(45) NULL,
  PRIMARY KEY (`CURP`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`TICKET` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TICKET` (
  `ID_TICKET` VARCHAR(18) NOT NULL,
  `NOMBRE_USUARIO` VARCHAR(45) NULL,
  `CURP` VARCHAR(45) NOT NULL,
  `FECHA` DATE NOT NULL,
  `ID_ASUNTO` INT NOT NULL,
  `ID_NIVEL` INT NOT NULL,
  `ID_MUNICIPIO` INT NOT NULL,
  `ESTATUS` VARCHAR(45) NULL,
  `TURNO` INT NULL,
  PRIMARY KEY (`ID_TICKET`),
  INDEX `ID_ASUNTO_idx` (`ID_ASUNTO` ASC) ,
  INDEX `ID_NIVEL_idx` (`ID_NIVEL` ASC) ,
  INDEX `ID_MUNIPIO_idx` (`ID_MUNICIPIO` ASC) ,
  INDEX `CURP_idx` (`CURP` ASC) ,
  CONSTRAINT `ID_ASUNTO`
    FOREIGN KEY (`ID_ASUNTO`)
    REFERENCES `mydb`.`ASUNTO` (`ID_ASUNTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_NIVEL`
    FOREIGN KEY (`ID_NIVEL`)
    REFERENCES `mydb`.`NIVELES` (`ID_NIVEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_MUNICIPIO`
    FOREIGN KEY (`ID_MUNICIPIO`)
    REFERENCES `mydb`.`MUNICIPIO` (`ID_MUNICIPIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CURP`
    FOREIGN KEY (`CURP`)
    REFERENCES `mydb`.`ALUMNO` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `mydb`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `NOMBRE_USUARIO` VARCHAR(45) NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `CONTRASEÑA` VARCHAR(45) NULL,
  PRIMARY KEY (`NOMBRE_USUARIO`))
ENGINE = InnoDB;

